name: "Adicionar novo evento 📅"
description: Utilize esta opção para adicionar um novo evento seguindo o padrão.
title: "adicionar evento"
labels: ["🗓️ evento:adicionar"]
body:
  - type: markdown
    attributes:
      value: |
        # Vamos criar um novo evento?

  - type: markdown
    attributes:
      value: |
        ## Informações Gerais do Evento

  - type: input
    id: nome_evento
    attributes:
      label: Nome do Evento
      description: Qual o nome do evento?
      placeholder: "ex: TDC 2025"
    validations:
      required: true

  - type: input
    id: site_evento
    attributes:
      label: Site do Evento
      description: Informe o site oficial do evento.
      placeholder: "ex: https://evento.com"
    validations:
      required: true

  - type: dropdown
    id: formato_evento
    attributes:
      label: Formato
      description: Selecione o formato do evento.
      multiple: false
      options:
        - Presencial
        - Híbrido
        - Online
    validations:
      required: true

  - type: input
    id: local_evento
    attributes:
      label: Local
      description: Informe o local do evento (ignorado se online).
      placeholder: "ex: Centro de Convenções"
  

  - type: input
    id: cidade_evento
    attributes:
      label: Cidade
      description: Cidade onde o evento será realizado.
      placeholder: "ex: São Paulo"
  
  - type: input
    id: estado_evento
    attributes:
      label: Estado
      description: Estado onde o evento será realizado.
      placeholder: "ex: SP"
    
  - type: input
    id: pais_evento
    attributes:
      label: País
      description: País onde o evento será realizado.
      placeholder: "ex: Brasil"
    
  - type: markdown
    attributes:
      value: |
        ## Quando o evento vai acontecer?

  - type: markdown
    attributes:
      value: |
        ## Período do Evento

  - type: input
    id: inicio_evento
    attributes:
      label: Início
      description: Data de início do evento (Ano-Mês-Dia).
      placeholder: "ex: 2025-09-02"
    validations:
      required: true

  - type: input
    id: fim_evento
    attributes:
      label: Fim
      description: Data de término do evento (Ano-Mês-Dia).
      placeholder: "ex: 2025-09-05"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Submissão de Atividades

  - type: input
    id: inicio_submissao
    attributes:
      label: Início da Submissão
      description: Data de início para submissão de atividades (Ano-Mês-Dia).
      placeholder: "ex: 2025-07-01"
    validations:
      required: true

  - type: input
    id: fim_submissao
    attributes:
      label: Fim da Submissão
      description: Data final para submissão de atividades (Ano-Mês-Dia).
      placeholder: "ex: 2025-07-31"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Tipos de Submissão

  - type: checkboxes
    id: tipos_submissao
    attributes:
      label: Tipos de submissão
      description: Selecione os tipos de atividades aceitas.
      options:
        - label: Palestra
        - label: Workshop
        - label: Lightning Talk
        - label: Painel
        - label: Tutorial
        - label: Minicurso
        - label: Sprint
        - label: Outros
    validations:
      required: true

  - type: input
    id: outros_submissao
    attributes:
      label: Outros (descreva)
      description: Caso tenha selecionado "Outros", descreva aqui.
      placeholder: "ex: Mesa redonda, Hackathon..."
    
