name: "Adicionar evento"
description: "Utilize essa opção para adicionar um novo evento!"
title: "Adiciona Evento: <NOME_DO_EVENTO>"
labels: ["🗓️ evento:adicionar"]
assignees: []
body:
  # =========================================================
  # 1) Informações básicas do evento
  # =========================================================
  - type: markdown
    attributes:
      value: |
        _Substituir `<NOME_DO_EVENTO>` pelo nome do evento a ser adicionado._
        _Exemplo: `Adiciona evento: Python Brasil 2025`_

        ## 1) Informações básicas do evento

  - type: input
    id: nome_evento
    attributes:
      label: Nome do Evento
      placeholder: "Python Cerrado"
    validations:
      required: true

  - type: input
    id: site_evento
    attributes:
      label: Site do Evento
      description: "URL do site oficial (inclua https://)."
      placeholder: "https://exemplo.org"
    validations:
      required: true

  # =========================================================
  # 2) Formato e Local
  # =========================================================
  - type: markdown
    attributes:
      value: "## 2) Formato e Local"

  - type: dropdown
    id: formato
    attributes:
      label: Formato do Evento
      options:
        - Presencial
        - Híbrido
        - Online
    validations:
      required: true

  - type: input
    id: cidade
    attributes:
      label: Cidade (deixe em branco se online)
      placeholder: "Brasília"

  - type: input
    id: estado
    attributes:
      label: Estado/Província (deixe em branco se online)
      description: "Sigla do estado ou província (ex.: DF, SP, RJ, MG)."
      placeholder: "DF"

  - type: input
    id: pais
    attributes:
      label: País (deixe em branco se online)
      description: "Código ISO-2 (ex.: BR, AR, PT, US)."
      placeholder: "BR"

  # =========================================================
  # 3) Datas do Evento
  # =========================================================
  - type: markdown
    attributes:
      value: |
        ## 3) Datas do Evento
        Primeiro e último dia de Evento. Caso o evento dure apenas 1 dia, repita o mesmo dia em 'primeiro' e 'último'.

  # =========================================================
  # 3.1) Primeiro dia
  # =========================================================
  - type: markdown
    attributes:
      value: "### 3.1) Primeiro dia"

  # Primeiro dia do evento
  - type: dropdown
    id: evento_ano_inicio
    attributes:
      label: Ano do primeiro dia de Evento
      options:
        - "2025"
        - "2026"
        - "2027"
        - "2028"
        - "2029"
        - "2030"
    validations:
      required: true

  - type: dropdown
    id: evento_mes_inicio
    attributes:
      label: Mês do primeiro dia de Evento
      options:
        - Janeiro
        - Fevereiro
        - Março
        - Abril
        - Maio
        - Junho
        - Julho
        - Agosto
        - Setembro
        - Outubro
        - Novembro
        - Dezembro
    validations:
      required: true

  - type: dropdown
    id: evento_dia_inicio
    attributes:
      label: Dia do primeiro dia de Evento
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
    validations:
      required: true

  # =========================================================
  # 3.2) Último dia
  # =========================================================
  - type: markdown
    attributes:
      value: "### 3.2) Último dia"

  - type: dropdown
    id: evento_ano_fim
    attributes:
      label: Ano do último dia de Evento
      description: "Se for evento de 1 dia, repita o mesmo ano."
      options:
        - "2025"
        - "2026"
        - "2027"
        - "2028"
        - "2029"
        - "2030"
    validations:
      required: true

  - type: dropdown
    id: evento_mes_fim
    attributes:
      label: Mês do último dia de Evento
      description: "Se for evento de 1 dia, repita o mesmo mês."
      options:
        - Janeiro
        - Fevereiro
        - Março
        - Abril
        - Maio
        - Junho
        - Julho
        - Agosto
        - Setembro
        - Outubro
        - Novembro
        - Dezembro
    validations:
      required: true

  - type: dropdown
    id: evento_dia_fim
    attributes:
      label: Dia do último dia de Evento
      description: "Se for evento de 1 dia, repita o mesmo dia."
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
    validations:
      required: true

  # =========================================================
  # 4) Período de Submissão de Atividades
  # =========================================================
  - type: markdown
    attributes:
      value: |
        ## 4) Período de Submissão de Atividades

  # =========================================================
  # 4.1) Primeiro dia
  # =========================================================
  - type: markdown
    attributes:
      value: "### 4.1) Primeiro dia"

  - type: dropdown
    id: sub_ano_inicio
    attributes:
      label: Ano do primeiro dia de Submissão
      options:
        - "2025"
        - "2026"
        - "2027"
        - "2028"
        - "2029"
        - "2030"
    validations:
      required: true

  - type: dropdown
    id: sub_mes_inicio
    attributes:
      label: Mês do primeiro dia de Submissão
      options:
        - Janeiro
        - Fevereiro
        - Março
        - Abril
        - Maio
        - Junho
        - Julho
        - Agosto
        - Setembro
        - Outubro
        - Novembro
        - Dezembro
    validations:
      required: true

  - type: dropdown
    id: sub_dia_inicio
    attributes:
      label: Dia do primeiro dia de Submissão
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
    validations:
      required: true

  # =========================================================
  # 4.2) Último dia
  # =========================================================
  - type: markdown
    attributes:
      value: "### 4.2) Último dia"

  - type: dropdown
    id: sub_ano_fim
    attributes:
      label: Ano do último dia de Submissão
      options:
        - "2025"
        - "2026"
        - "2027"
        - "2028"
        - "2029"
        - "2030"
    validations:
      required: true

  - type: dropdown
    id: sub_mes_fim
    attributes:
      label: Mês do último dia de Submissão
      options:
        - Janeiro
        - Fevereiro
        - Março
        - Abril
        - Maio
        - Junho
        - Julho
        - Agosto
        - Setembro
        - Outubro
        - Novembro
        - Dezembro
    validations:
      required: true

  - type: dropdown
    id: sub_dia_fim
    attributes:
      label: Dia do último dia de Submissão
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
    validations:
      required: true

  # =========================================================
  # 5) Tipos de Submissão
  # =========================================================
  - type: markdown
    attributes:
      value: "## 5) Tipos de Submissão (marque quantos quiser)"

  - type: checkboxes
    id: tipos_submissao
    attributes:
      label: Tipos de Submissão aceitos
      options:
        - label: Palestra
        - label: Workshop
        - label: Lightning talk
        - label: Painel
        - label: Tutorial
        - label: Minicurso
        - label: Outros (especificar abaixo)

  - type: input
    id: tipos_submissao_outros
    attributes:
      label: Se marcou “Outros”, especifique
      placeholder: "Ex.: pôster, mesa redonda, oficina mão na massa"
      description: "Opcional"
