jobs:
  export-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
       
      - name: Exporta issues
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh issue list --repo ${{ github.repository }} --limit 100 -- name,body,labels --json name,body,labels > issues.json
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Verifica tipo da issue
        run: |
          python <<EOF
          import json
          with open('issues.json') as f:
              issues = json.load(f)
          for issue in issues:
              if 'Vamos adicionar um novo evento?😁' in [label['name'] for label in issue.get('labels', [])]:
                  os.system(python script/adicionar_evento.py )
              elif 'Vamos atualizar um evento existente?' in [label['name'] for label in issue.get('labels', [])]:
                  os.system(python script/atualizar_evento.py)
              elif 'Remover evento ❌' in [label['name'] for label in issue.get('labels', [])]:
                  os.system(python script/remover_evento.py)
              elif 'Atualizar evento' in [label['name'] for label in issue.get('labels', [])]:
                  os.system(python script/atualizar_evento.py)
           
          EOF
      - name: Cria branch
        run: |
          python <<EOF
          import json, os
          with open('issues.json') as f:
              issues = json.load(f)
          for issue in issues:
              import re
              nome_branch = re.sub(r'\W+', '_', issue.get("name", ""))
              os.system(f"git switch -c {nome_branch}")
          EOF
        
      - name: Pull
        run: git pull origin main
      - name: Commit e push
        run: |
          python <<EOF
          import json, os
          with open('issues.json') as f:
              issues = json.load(f)
          for issue in issues:
              import re
              nome_branch = re.sub(r'\W+', '_', issue.get("name", ""))
              mensagem_commit = f"{issue.get('name', '')} - {issue.get('body', 'event_name')}"
              os.system('git config --local user.email "jlprcarvalho@gmail.com"')
              os.system('git config --local user.name "GitHub Actions"')
              os.system('git add .')
              os.system(f'git commit -m "{mensagem_commit}"')
              os.system(f'git push origin {nome_branch}')
        
          EOF
      - name: Exclui issues.json
        run: rm issues.json