name: Exibir informações da Issue

on:
  issues:
    types: [opened, edited]

jobs:
  mostrar-info:
    runs-on: ubuntu-latest
    env:
      NOME_ARQUIVO: issue_data.json
    steps:
      - name: Verificar checkout do repositório
        uses: actions/checkout@v4

      - name: Converter issue para JSON
        uses: zentered/issue-forms-body-parser@v2.2.0
        id: parse

      - name: Salvar dados da issue em um arquivo
        run: |
          echo '${{ steps.parse.outputs.data }}' > $NOME_ARQUIVO
        
  
          echo "Número da issue: ${{ github.event.issue.number }}"
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"

      - name: Validar evento na issue
        run: |
          python3 script/validar_evento.py >> $GITHUB_OUTPUT
          if [$GITHUB_OUTPUT == 1]; then
            echo "A issue não é válida."
            exit 1
          else
            echo "A issue é válida."
          fi
  
          # Adicione aqui o código para processar a issue conforme necessário
