name: Exibir informações da Issue

on:
  issues:
    types: [opened, edited]
    

jobs:
  mostrar-info:
    runs-on: ubuntu-latest
    env:
      NOME_ARQUIVO: issue_data.json
    steps:
      - name: Verificar checkout do repositório
        uses: actions/checkout@v6

      - name: Converter issue para JSON
        uses: zentered/issue-forms-body-parser@v2.2.0
        id: parse

      - name: Salvar dados da issue em um arquivo
        run: |
          echo '${{ steps.parse.outputs.data }}' > $NOME_ARQUIVO
        
  
          echo "Número da issue: ${{ github.event.issue.number }}"
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"

      - name: Executar script para validar evento
        run: |
          python3 backend/validar_evento.py ${{github.workspace}}/$NOME_ARQUIVO

      - name: Executar script de adicionar evento
        run: |
          python3 backend/adicionar_evento.py ${{github.workspace}}/$NOME_ARQUIVO
