name: Exibir informações da Issue

on:
  issues:
    types: [opened, edited]

jobs:
  mostrar-info:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir número e labels da issue
        run: |
          echo "Número da issue: ${{ github.event.issue.number }}"
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"
      
      - name: Verificar se a issue tem a label 'evento:adicionar'
        if: contains(join(github.event.issue.labels.*.name, ','), 'evento:adicionar')
        run: |
          echo "A issue contém a label 'evento:adicionar'."
          # Adicione aqui o código para processar a issue conforme necessário

      - name: Verificar se a issue NÃO tem a label 'evento:adicionar'
        if: ${{ !contains(join(github.event.issue.labels.*.name, ','), 'evento:adicionar') }}
        run: |
          echo "A issue não contém a label 'evento:adicionar'."
          #  Abstrair isso para arquivo .py
